apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: "mc.closetbox.us"
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mc-test-minecraft
            port:
              number: 25565